#160587139 User login and logout
shaolinmkz/fast-food-fast pull request #17
Opened 2018-09-21 16:57 UTC by shaolinmkz

#### What does this PR do?
Have the login and logout route implemented

#### Description of Task to be completed?
Having the following api user routes functioning:
GET `host:port/api/v2/auth/users`
POST `host:port/api/v2/auth/signup`
POST `host:port/api/v2/auth/login`
POST `host:port/api/v2/auth/logout`

#### How should this be manually tested?
After cloning the repo, cd into it and RUN `npm start:dev` OR `npm start`
* Using Postman test every endpoint above with this header:
key: Content-Type value: application/json

#### What are the relevant pivotal tracker stories?
#160587139

2018-09-21 17:24 UTC, KaiserPhemi requested changes
#### Critical
Implement feedback

2018-09-21 17:24 UTC, KaiserPhemi commented on server/Helper/loopHelper.js
> +}
#### Nitpick
New line after the last line.

2018-09-21 17:24 UTC, KaiserPhemi commented on server/middlewares/usersValidation.js
> +	// for (i = 0; i < email.length; i++){
#### Critical
Remove all dead codes not needed instead of commenting them

2018-09-21 17:24 UTC, KaiserPhemi commented on server/middlewares/usersValidation.js
> +// };
#### Nitpick
New Line

2018-09-21 17:24 UTC, KaiserPhemi commented on server/routes/adminRoutes.js
> +// import express from "express";
#### Critical 
What's this file doing here if everything within it is commented out?

2018-09-21 17:24 UTC, KaiserPhemi commented on test/userTestRoutes.js
> +});
#### Nitpick
New line

2018-09-21 19:19 UTC, shaolinmkz commented on server/routes/adminRoutes.js
> +// import express from "express";
I left the admin route commented because I will still be to use it in the feature... I just created the path structure for start.

2018-09-21 19:21 UTC, shaolinmkz commented on server/middlewares/usersValidation.js
> +	// for (i = 0; i < email.length; i++){
I will do that immediately...

2018-09-22 03:06 UTC, shaolinmkz commented on server/Helper/loopHelper.js
> +}
I deleted this looperHelper file ... it doesnt exist for now

2018-09-22 03:23 UTC, shaolinmkz commented on test/userTestRoutes.js
> +});
Fixed

2018-09-22 18:43 UTC, KaiserPhemi requested changes
I've got a few concerns
- Your code wasn't documented properly using `jsdoc`. You can check [here](http://usejsdoc.org/about-getting-started.html)
- Some of your logic need refactoring. I saw some nested for loops. 
- It appears you didn't write a lot of test.

Please fix these and make sure your app/endpoints are working

2018-09-22 18:43 UTC, KaiserPhemi commented on server/auth/auth.js
> +}
#### Nitpick
New line

2018-09-24 13:49 UTC, KaiserPhemi approved these changes
#LGTM

2018-09-24 21:13 UTC, merged